sudo: required

services:
  - docker

env:
  global:
  - IMAGE_NAME=gurkalov/ubuntu-ssh
  - VERSION=latest

before_script:
- make pull version=${VERSION}

script:
- make test version=${VERSION}

after_script:
- docker images

before_deploy:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${VERSION}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${VERSION}"
  on:
    branch: dev
